version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - BASE_MODEL=${BASE_MODEL:-claude-3-sonnet-20240229}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - PYTHONPATH=/app
    restart: unless-stopped