services:
  fast-api-server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app/server
      - ./client:/app/client
      - ./mcp_config.json:/app/mcp_config.json
    command: uv run -- uvicorn server.server:app --host 0.0.0.0 --port 8000